project/apps/cases/urls.py
from django.urls import path, include
from .import views 

app_name = 'cases'
urlpatterns = [
    path('', views.case_list, name='case_list'),
    path('<int:case_id>/', views.case_view, name='case_view'),
    # path('<int:case_id>/', views.case_add, name='case_add'),
    # path('section/', views.section_list, name='section_list'),    
    # path('<int:case_id>/section/<int:section_id>/', views.section_view, name='section_view'),    
    # path('<int:case_id>/section/<int:section_id>/caseparam/<int:caseparam_id>/', views.caseparam_view, name='caseparam_view'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [    
    path('__debug__/', include('debug_toolbar.urls')), #Мод для дебага
    path('admin/', admin.site.urls),
	path('cases/', include('cases.urls')),
	path('', include('cases.urls')),
]

project/apps/cases/models.py
from django.db import models
# from django.contrib.auth.models import User
# from django.db.models import Q
# import datetime

# Модели: Case, Section, Parameter, Period, Data

# Модель Кейс - это самая главная модель которая содержит в себе все параметры, работы, файлы, и т.д
class Case(models.Model):
    Case_ID = models.AutoField(primary_key=True)
    Case_Name = models.CharField('Название кейса', max_length=50)
    Case_Comment = models.TextField('Коментарий')

    def __str__(self):
        return self.Case_Name

    def get_absolute_url(self):  # Отвечает за ссылку 'Смотреть на сайте' - переход от админки на сайт
        return f'/cases/{self.Case_ID}/'

    class Meta:
        verbose_name = 'Кейс'
        verbose_name_plural = 'Кейсы'


# Раздел кейса, нужен для того чтобы обозначать имена разделов, если такие понадобятся
# Содержит в себе параметры
class Section(models.Model):    
    Section_ID = models.AutoField(primary_key=True)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    Section_Name = models.CharField('Название раздела', max_length=100)

    def __str__(self):
        return self.Section_Name

    # def get_absolute_url(self):  # Отвечает за ссылку 'Смотреть на сайте' - переход от админки на сайт
    #     return f'/cases/section/{self.section_id}/'

    class Meta:
        verbose_name = 'Раздел кейса'
        verbose_name_plural = 'Разделы кейса'


# Параметр кейса, нужен для того чтобы отображать имя, комментарий
class Parameter(models.Model): # Бывший CaseParam
    Parameter_ID = models.AutoField(primary_key=True)
    section = models.ManyToManyField(Section)# связь многие ко многим
    Parameter_Name = models.CharField('Название', max_length=100)
    Parameter_Comment = models.TextField('Коментарий')
    Parameter_Sort = models.FloatField('Вес при сортировке', default=Parameter_ID, null=True) # По умолчанию равен ID - то есть в порядке создания
    Parameter_Var_Name = models.CharField('Название переменной', default="", max_length=100)

    def __str__(self):
        return self.Parameter_Name

    class Meta:
        verbose_name = 'Параметр'
        verbose_name_plural = 'Параметры'


# Период сбора данных - периоды в промежутках которых были собранны данные
class Period(models.Model):
    Period_ID = models.AutoField(primary_key=True)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    Period_Name = models.CharField('Период', max_length=100)
    Period_Sort = models.FloatField('Вес при сортировке', default=Period_ID, null=True) # По умолчанию равен ID - то есть в порядке создания
    
    def __str__(self):
        return self.Period_Name

    class Meta:
        verbose_name = 'Период'
        verbose_name_plural = 'Периоды'


# Данные - значения параметра за определенный период
class Data(models.Model):
    parameter = models.ForeignKey(Parameter, on_delete=models.CASCADE)
    period = models.ForeignKey(Period, on_delete=models.CASCADE)    
    Data_ID = models.AutoField(primary_key=True)
    Data_Value = models.FloatField('Значение', default=0, null=True)    
    
    def __str__(self):
        return str(self.Data_Value)

    class Meta:
        verbose_name = 'Значение'
        verbose_name_plural = 'Значения'

project/apps/cases/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from .models import  Case, Section, Parameter, Period, Data

def case_list(request):
    case_list = Case.objects.all()
    return render(request, 'cases/case_list.html', {'case_list': case_list})

def case_view(request, case_id):
    try: case = Case.objects.get(Case_ID = case_id)
    except: raise Http404("Кейс " + str(case_id) + " не найден" + Case.objects.get(Case_ID = case_id) )
    return render(request, 'cases/case_view.html', {
        'case': case, 
        'section_line_in_case': case.section_set.all(), 
        'period_column_in_case': case.period_set.all()
        })
    
# def section_list(request):
#     return render(request, 'cases/section_list.html', {
#         'section_list': Section.objects.all()
#         })
    
# def section_view(request, case_id, section_id):
#     try: section = Section.objects.get(id = section_id)
#     except: raise Http404("Раздел не найден")
#     return render(request, 'cases/section_view.html', {'case': Case.objects.get(id = case_id), 'section': section, 'caseparam_list_in_section': section.caseparam_set.all()})

# def caseparam_view(request, case_id, section_id, caseparam_id):
#     try: caseparam = CaseParam.objects.get(id = caseparam_id)
#     except: raise Http404("Раздел не найден")
#     return render(request, 'cases/caseparam_view.html', {'case': Case.objects.get(id = case_id), 'section': Section.objects.get(id = section_id), 'caseparam': caseparam, 'dateparam_list_in_caseparam': caseparam.dateparam_set.all()})

project/templates/base.html
<!DOCTYPE html>
<html>
{% load global_context %}
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} Кейсы {% endblock %}</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="icon" href="https://www.susu.ru/sites/default/files/favicon_0.ico" type="image/x-icon">
  <style type="text/css">
  #box {
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    z-index: 999;
    display: none;
  }
  #content {
    width: 500px; /* Ширина слоя */
    margin: 0 auto 50px; /* Выравнивание по центру */
  }
  #footer {
    position: fixed; /* Фиксированное положение */
    left: 0; bottom: 0; /* Левый нижний угол */
    padding: 10px; /* Поля вокруг текста */
    background: #39b54a; /* Цвет фона */
    color: #fff; /* Цвет текста */
    width: 100%; /* Ширина слоя */
   }
  #box-inner {
    position: absolute;
    left: 0px;
    right: 0px;
    top: 0px;
    bottom: 0px;
    background: blue;
    opacity: 0.3;
    display: none;
  }
  #box #container {
    position: absolute;
    top: 0; bottom: 0; right: 0; left: 0; /* центрирование */
    margin: auto;  /* центрирование */
    height: 15em;
    width: 25em;
    border: 1px solid black;
    background: white;
    padding: 1%; 
  }
  iframe {
    width: 100%;
    height: 100%;
    border: none;
  }
  </style>
</head>



<body style="background: rgba(0, 0, 0, 0) url(https://www.toptal.com/designers/subtlepatterns/patterns/double-bubble-outline.png) repeat scroll 0% 0%;">    
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <img width="25%" href="{% url 'cases:case_list' %}" height="25%" src="https://www.susu.ru/sites/all/themes/boot2017/logo/ru/wider/2400.png">   
      <!-- <h4 class="my-0 col-md-3 md-mr-auto font-weight-normal">Высшая школа экономики и управления </h4> -->
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'cases:case_list' %}">Кейсы</a>
        <!-- {%if request.user|has_group:"Преподаватель" %} -->
        <!-- <a class="p-2 text-dark" href="{%url 'cases:students' %}">Задания студентов</a>  -->
        <!-- <a class="p-2 text-dark" href="{% url 'cases:create' %}">Управление шаблонами</a> -->
        <!-- <a class= "p-2 text-dark" href ="{% url 'cases:files' %}">Файлы</a> -->
        <!-- {%endif%} -->

        <!-- {%if not request.user|has_group:"Преподаватель" and user.is_superuser %} -->
          <a class= "p-2 text-dark" href ="/admin"><b>Перейти в админку</b></a>
        <!-- {%endif%} -->
      </nav>
  </div>
  <div style="min-height:650px;">
    {% block content %}{% endblock %}
    <style>  
    /* Стили используемые в шаблонах */
      .column { 
        text-align: center;
      }
      
      td {
        padding: 1px;
        padding-right: 10px;
        border: 1px solid lightgray;
      }
      
      th {
        padding: 1px;
      }
      </style>
  </div>

    <footer style=" bottom:0; ">
      <div style='background: rgba(10, 10, 100, 0) url("https://www.toptal.com/designers/subtlepatterns/patterns/double-bubble-outline.png") repeat scroll 0% 11%;' style="margin-left: 50px;">
        <hr />
        <p>Россия, 454080 <a href="https://www.susu.ru/ru/about/campus" title="Карта">Челябинск, проспект Ленина, 76</a><br>
          Тел./факс: +7 (351) 267-99-00<br>
          E-mail: <a href="mailto:info@susu.ru" processed="processed">info@susu.ru</a><br>
          Центр информации и связей с общественностью: <a href="mailto:press@susu.ru" processed="processed">press@susu.ru</a><br>
          Техподдержка сайта: <a href="mailto:support@susu.ru" processed="processed">support@susu.ru</a></p>
      </div>
    </footer>
  </body>
</html>

project/templates/cases/case_add.html
{% extends 'base.html' %}

{% block title %} {{case.Case_Name}} {% endblock %}
{% load static %}

{% block content %}

  {% if case_list %}
    {% for case in case_list %}
      <a href="{% url 'cases:detail' case.id%}">{{case.Case_Name}}</a>
    {% endfor%}
  {% else %}
    Кейсов нет
  {% endif %}


{% endblock %}

project/templates/cases/case_edit.html
{% extends 'base.html' %}

{% block title %} {{case.Case_Name}} {% endblock %}
{% load global_context %}
{% load static %}

{% block content %}

<p class="font-weight-bold"> Название кейса: {{case.Case_Name}}</p>
<p><b>Комментарий: </b>{{case.Case_Comment}}</p>
<table>  
  <thead> <!-- Вывод Периодов в заголовок -->
    {% if period_column_in_case %} 
      <col width="200"> <!-- Ширина первого столбца -->
      <tr>
        <th>Параметр\Период</th>
        {% for period in period_column_in_case %}
          <th class="column">{{period.Period_Name}}</th>
        {% endfor %}
      </tr>
    {%endif%}
  </thead>
  <tbody>    
    <form method="POST">      
      {% csrf_token %}
        {% if section_line_in_case %} 
          {% for section in section_line_in_case %}             
            <tr> <!-- Вывод Разделов как подзаголовков -->
              <th class="column-1">
                <!-- <a href=" url 'cases:section_view' case.Case_ID section.Section_ID %}"> -->
                  {{section.Section_Name}}
                <!-- </a>       -->
              </th>
            </tr>        
            {% for parameter in section.parameter_set.all %}
              <tr>
                {% if parameter %}              
                  <td> <!-- Вывод Параметров как строк -->
                    {{parameter.Parameter_Name}}        
                  </td>
                    {%for data in parameter.data_set.all|sort:'period'%}
                    <td class="column">
                      {{data.Data_Value}}
                    </td>
                  {%endfor%}
                {% endif %}
              </tr> 
            {% endfor %}               
          {% endfor %}
        {% endif %}
      </form>
    </tbody>   
  
</table>

{% endblock %}

project/templates/cases/case_list.html
{% extends 'base.html' %}

{% block title %} Кейсы {% endblock %}
{% load global_context %}
{% load static %}

{% block content %}
  {% if case_list %}
    {% for case in case_list %}
      <a href="{% url 'cases:case_view' case.Case_ID %}">{{case.Case_Name}}</a>  
      <br>    
    {% endfor%}
  {% else %}
    Кейсов нет
  {% endif %}
{% endblock %}

project/templates/cases/case_view.html
{% extends 'base.html' %}

{% block title %} {{case.Case_Name}} {% endblock %}
{% load global_context %}
{% load static %}

{% block content %}

<p class="font-weight-bold"> Название кейса: {{case.Case_Name}}</p>
<p><b>Комментарий: </b>{{case.Case_Comment}}</p>
<table>  
  <thead> <!-- Вывод Периодов в заголовок -->
    {% if period_column_in_case %} 
      <col width="200"> <!-- Ширина первого столбца -->
      <tr>
        <th>Параметр\Период</th>
        {% for period in period_column_in_case %}
          <th class="column">{{period.Period_Name}}</th>
        {% endfor %}
      </tr>
    {%endif%}
  </thead>
  <tbody>
    {% if section_line_in_case %} 
      {% for section in section_line_in_case %}             
        <tr> <!-- Вывод Разделов как подзаголовков -->
          <th class="column-1">
            <!-- <a href=" url 'cases:section_view' case.Case_ID section.Section_ID %}"> -->
              {{section.Section_Name}}
            <!-- </a>       -->
          </th>
        </tr>        
        {% for parameter in section.parameter_set.all %}
          <tr>
            {% if parameter %}              
              <td> <!-- Вывод Параметров как строк -->
                {{parameter.Parameter_Name}}        
              </td>
                {%for data in parameter.data_set.all|sort:'period'%}
                <td class="column">
                  {{data.Data_Value}}
                </td>
              {%endfor%}
            {% endif %}
          </tr> 
        {% endfor %}               
      {% endfor %}
    {% endif %}
  </tbody>   
  
</table>

{% endblock %}