Economy/project/apps/cases/urls.py
from django.urls import path, include

from .import views 

app_name = 'cases'
urlpatterns = [
    path('', views.case_list, name='case_list'),
    path('case_add/', views.case_add, name='case_add'),
    path('<int:case_id>/', views.case_view, name='case_view'),
    path('<int:case_id>/case_edit', views.case_edit, name='case_edit'),
    # path('<int:case_id>/period_add/', views.period_add, name='period_add'),
    # path('<int:case_id>/section_add/', views.section_add, name='section_add'),
    # path('<int:case_id>/parameter_add/', views.parameter_add, name='parameter_add'),
    # path('<int:case_id>/section_parameter/', views.section_parameter, name='section_parameter'),
    # path('<int:case_id>/section/<int:section_id>/', views.section_view, name='section_view'), 
    # path('<int:case_id>/section_edit/<int:section_id>/', views.section_edit, name='section_edit'),
]

Economy/project/apps/students/urls.py
from django.urls import path, include

from .import views 

app_name = 'students'
urlpatterns = [
    path('', views.case_list, name='case_list'),
    # path('case_add/', views.case_add, name='case_add'),
    # path('<int:case_id>/', views.case_view, name='case_view'),
    # path('<int:case_id>/case_edit', views.case_edit, name='case_edit'),
    # path('<int:case_id>/period_add/', views.period_add, name='period_add'),
    # path('<int:case_id>/section_add/', views.section_add, name='section_add'),
    # path('<int:case_id>/parameter_add/', views.parameter_add, name='parameter_add'),
    # path('<int:case_id>/section_parameter/', views.section_parameter, name='section_parameter'),
    # path('<int:case_id>/section/<int:section_id>/', views.section_view, name='section_view'), 
    # path('<int:case_id>/section_edit/<int:section_id>/', views.section_edit, name='section_edit'),
]

Economy/project/apps/teachers/urls.py
from django.urls import path, include

from .import views 

app_name = 'teachers'
urlpatterns = [
    path('', views.case_list, name='case_list'),
    # path('case_add/', views.case_add, name='case_add'),
    # path('<int:case_id>/', views.case_view, name='case_view'),
    # path('<int:case_id>/case_edit', views.case_edit, name='case_edit'),
    # path('<int:case_id>/period_add/', views.period_add, name='period_add'),
    # path('<int:case_id>/section_add/', views.section_add, name='section_add'),
    # path('<int:case_id>/parameter_add/', views.parameter_add, name='parameter_add'),
    # path('<int:case_id>/section_parameter/', views.section_parameter, name='section_parameter'),
    # path('<int:case_id>/section/<int:section_id>/', views.section_view, name='section_view'), 
    # path('<int:case_id>/section_edit/<int:section_id>/', views.section_edit, name='section_edit'),
]

Economy/project/apps/cases/models.py
from django.db import models
from django.contrib.auth.models import User, Group
# from django.db.models import Q
# import datetime

# Модели: Case, Section, Parameter, Period, Data

# Модель Кейс - это самая главная модель которая содержит в себе все параметры, работы, файлы, и т.д
class Case(models.Model):
    Case_ID = models.AutoField(primary_key=True)
    Case_Name = models.CharField('Название кейса', max_length=50)
    Case_Comment = models.TextField('Коментарий')
    Case_Parent = models.IntegerField('Родительский кейс', default=-1)  

    def __str__(self):
        return self.Case_Name

    def get_absolute_url(self):  # Отвечает за ссылку 'Смотреть на сайте' - переход от админки на сайт
        return f'/cases/{self.Case_ID}/'

    class Meta:
        verbose_name = 'Кейс'
        verbose_name_plural = 'Кейсы'


# Раздел кейса, нужен для того чтобы обозначать имена разделов, если такие понадобятся
# Содержит в себе параметры
class Section(models.Model):    
    Section_ID = models.AutoField(primary_key=True)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    Section_Name = models.CharField('Название раздела', max_length=100)
    Section_Sort = models.FloatField('Вес при сортировке', default=Section_ID, null=True) # По умолчанию равен ID - то есть в порядке создания

    def __str__(self):
        return self.Section_Name

    def get_absolute_url(self):  # Отвечает за ссылку 'Смотреть на сайте' - переход от админки на сайт
        return f'/cases/section/{self.Section_ID}/'

    class Meta:
        verbose_name = 'Раздел кейса'
        verbose_name_plural = 'Разделы кейса'


# Параметр кейса, нужен для того чтобы отображать имя, комментарий
class Parameter(models.Model): # Бывший CaseParam
    Parameter_ID = models.AutoField(primary_key=True)
    section = models.ManyToManyField(Section) # Cвязь многие ко многим
    Parameter_Name = models.CharField('Название', max_length=100)
    Parameter_Comment = models.TextField('Коментарий')
    Parameter_Sort = models.FloatField('Вес при сортировке', default=Parameter_ID, null=True) # По умолчанию равен ID - то есть в порядке создания
    # Parameter_Var = models.CharField('Название переменной', max_length=100) отделяем название переменной, как отдельную сущноть

    def __str__(self):
        return self.Parameter_Name

    class Meta:
        verbose_name = 'Параметр'
        verbose_name_plural = 'Параметры'


# Период сбора данных - периоды в промежутках которых были собранны данные
class Period(models.Model):
    Period_ID = models.AutoField(primary_key=True)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    Period_Name = models.CharField('Период', max_length=100)
    Period_Sort = models.FloatField('Вес при сортировке', default=Period_ID, null=True) # По умолчанию равен ID - то есть в порядке создания
    
    def __str__(self):
        return self.Period_Name

    class Meta:
        verbose_name = 'Период'
        verbose_name_plural = 'Периоды'


# Данные - значения параметра за определенный период
class Data(models.Model):
    parameter = models.ForeignKey(Parameter, on_delete=models.CASCADE)
    period = models.ForeignKey(Period, on_delete=models.CASCADE)    
    Data_ID = models.AutoField(primary_key=True)
    Data_Value = models.FloatField('Значение', default=0, null=True, blank=True)
    
    def __str__(self):
        return str(self.Data_Value)

    class Meta:
        verbose_name = 'Значение'
        verbose_name_plural = 'Значения'
        

# Переменные
class Variable(models.Model):
    Variable_ID = models.AutoField(primary_key=True)
    parameter = models.OneToOneField(Parameter, on_delete=models.CASCADE)
    Variable_Name = models.CharField('Переменная', max_length= 100)

    def __str__(self):
        return self.Variable_Name

    class Meta:
        verbose_name = 'Переменная'
        verbose_name_plural = 'Переменные'


# Формулы - модель для связи формулы с Переменными
class Formula(models.Model):
    Formula_ID = models.AutoField(primary_key=True)
    parameter = models.OneToOneField(Parameter, on_delete=models.CASCADE)
    variable = models.ManyToManyField(Variable) # Cвязь многие ко многим
    Formula_Name = models.CharField('Формула', max_length= 100)

    def __str__(self):
        return self.Formula_Name
    
    class Meta:
        verbose_name = 'Формула'
        verbose_name_plural = 'Формулы'


# Параметр работы, содержит в себе ссылку на кейс, так же содержит в себе имя работы которое
# отображается только у студента
# class JobParam(models.Model):
#     Case = models.ForeignKey(Case, on_delete=models.CASCADE)
#     Param_Name = models.CharField('Наименование', max_length=50)
#     Param_Help = models.CharField('Коментарий', max_length=1000)
#     Param_TrueValue = models.BooleanField()
#     Param_Period = models.DateField('Дата создания')

#     def __str__(self):
#         return self.Param_Name

#     class Meta:
#         verbose_name = 'Рабочий параметр'
#         verbose_name_plural = 'Рабочие параметры'

# Статус работы - типовое отношение пользователя к кейсу (например - редактирование, просмотр, на проверке, и пр.) 
# с сылкой на группу - для доступа к 
class Status(models.Model):
    Status_ID = models.AutoField(primary_key=True)
    Status_Name = models.CharField('Статус работы', max_length=50)
    Status_Comment = models.TextField('Коментарий')
    group = models.OneToOneField(Group, on_delete=models.CASCADE)

    def __str__(self):
        return self.Status_Name

    class Meta:
        verbose_name = 'Статус работы'
        verbose_name_plural = 'Статусы работы'

# Работа - модель для связи кейсов и пользователей, с указанием статуса отношения к кейсу
class Job(models.Model):
    Job_ID = models.AutoField(primary_key=True)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)

    def __str__(self):
        return self.status.Status_Name

    class Meta:
        verbose_name = 'Статус кейса'
        verbose_name_plural = 'Статусы кейса'

Economy/project/apps/students/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.contrib import messages
from cases.models import  Case, Section, Parameter, Period, Data, Formula, Variable, Job, Status
from cases.form import Create_Case_Form, Create_Period_Form, Create_Section_Form, Create_Parameter_Form, Edit_Case_Form, Edit_Section_Form

# Список всех кейсов
@login_required
def case_list(request):
    return render(request, 'cases/case_list.html', {'case_list': Case.objects.all()})

Economy/project/apps/teachers/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.contrib import messages
from cases.models import  Case, Section, Parameter, Period, Data, Formula, Variable, Job, Status
from cases.form import Create_Case_Form, Create_Period_Form, Create_Section_Form, Create_Parameter_Form, Edit_Case_Form, Edit_Section_Form

# Список всех кейсов
@login_required
def case_list(request):
    # if request.user.groups.filter(name='Students').exists():
    user = request.user
    job = Job.objects.all()
    case_list = Case.objects.all()
    # user.job.case.all()
    # Case.objects.all()
        # return redirect('students:case_list')
    # elif request.user.is_superuser:
        # return redirect('admin/')
    # elif request.user.groups.filter(name='Teachers').exists():
        # return redirect('teachers:case_list')
    # else:
        # return redirect('login/')
    case_data = {
        'case_list': case_list,
        'users': user,
        'job': job,
    }
    return render(request, 'cases/case_list.html', case_data )

Economy/project/templates/cases/case_add.html
{% extends 'base.html' %}

{% block title %} Создание нового кейса {% endblock %}
{% load static %}

{% block content %}

<div class="container">
  <h2> Формирование кейса </h2>  
  <div class="row justify-content-md-cente border">
      <div class="container">
        <div class="row justify-content-md-center">
          <div class="container-fluid">
            <form method="POST">
              {%csrf_token%}
              <br>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="">Название кейса:</span>
                </div>
                <input 
                class="form-control"  
                type="text" 
                name="Case_Name" 
                maxlength="500" 
                required=""
                >
              </div>
              <br>
              <div class="input-group">
                <textarea 
                  class="form-control"  
                  name="Case_Comment" 
                  maxlength="300" 
                  required="" 
                  id="id_Case_Comment"></textarea>
              </div>
              <br>
              <button type="submit" class="btn btn-primary">Создать</button>
              <input type="button" class="btn btn-primary" onclick="history.back();" value="Отмена"/>
              <br>
            </form>
          </div>
        </div>
      </div>
  </div>
</div>
{% endblock %}


Economy/project/templates/cases/case_edit.html
{% extends 'base.html' %}

{% block title %} {{case.Case_Name}} {% endblock %}
{% load global_context %}
{% load static %}

{% block content %}
<form method="POST">
  {%csrf_token%}
  <div> <!-- Кнопки управления -->
    <input class="btn btn-outline-success" type="submit" name="save_case" value="Сохранить">
    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#BackModal">Назад</button>
    <input class="btn btn-outline-primary" type="submit" name="section_add" value="Добавить раздел">
    <input class="btn btn-outline-primary" type="submit" name="period_add" value="Добавить период">
    {% comment %} 
    <button type="button" class="btn btn-lg btn-danger" data-bs-toggle="popover" title="Заголовок всплывающего сообщения" data-bs-content="А вот и потрясающий контент. Это очень интересно. Правильно?">Нажмите, чтобы переключить всплывающее окно</button>
    <a tabindex="0" class="btn btn-lg btn-danger" role="button" data-bs-toggle="popover" data-bs-trigger="focus" title="Отклоняемое всплывающее окно" data-bs-content="А вот и потрясающий контент. Это очень интересно. Правильно?">Отклоняемое всплывающее окно</a>
     {% endcomment %}
    {% comment %} <a class="btn btn-outline-info" href="{% url 'cases:section_parameter' case.Case_ID %}">Изменить зависимости разделов и параметров</a> {% endcomment %}
  </div>
  <p class="font-weight-bold"> Название кейса:
    <input
      class="form-control" 
      type="text"
      name="Case_{{case.Case_ID}}"
      value="{{case.Case_Name}}">
  </p>
  <p class="font-weight-bold">
    <b>
      Комментарий:
    </b>
    <input
      class="form-control" 
      type="text"
      name="Case_Comment_{{case.Case_ID}}"
      value="{{case.Case_Comment}}">
  </p>
  <table>
    {% include 'cases/tbody/thead_edit.html' %} <!-- Вывод заголовока -->    
    <tbody>
      {% if case.section_set.all %} 
        {% for section in case.section_set.all|sort:'Section_Sort' %}
          {% if not section|is_default_section %}
            <tr> <!-- Вывод Разделов как подзаголовков, кроме __default -->
              <th class="column-1">
                  {% comment %} {{section.Section_Name}} {% endcomment %}
                <!-- Изменене раздела -->
                  {% comment %} <a class="btn btn-outline-success" href="{% url 'cases:section_edit' case.Case_ID section.Section_ID %}">              
                    &#9997
                  </a> {% endcomment %}
                <input
                  class="form-control"
                  type="text"
                  name="Section_{{section.Section_ID}}"
                  value="{{section.Section_Name}}">
              </th>
              <th>
                <input
                  class="btn btn-primary" 
                  type="submit" 
                  name="parameter_add_in_{{section.Section_ID}}"
                  value="Добавить параметр"
                  {% comment %} {{section.Section_Name}} {% endcomment %}
                  >
              </th>
            </tr>
            {% include 'cases/tbody/tbody_section_edit.html' %} <!-- Вывод секций -->
          {% endif %}
        {% endfor %}
      {% endif %}
    </tbody>
  </table>
<!-- Модальное окно Назад -->
<div class="modal fade" id="BackModal" tabindex="-1" aria-labelledby="BackModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="BackModalLabel">Выйти из кейса '{{case.Case_Name}}' без сохранения?</h5>        
      </div>
      {% comment %} <div class="modal-body"></div> {% endcomment %}
      <div class="modal-footer">
        <a class="btn btn-outline-danger" href="{% url 'cases:case_view' case.Case_ID %}">Да</a>
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal" aria-label="Закрыть">Нет</button>
        {% comment %} <input class="btn btn-outline-success" type="submit" name="save_case" value="Сохранить"> {% endcomment %}
        <!-- Реализовать возможность выхода с сохранением -->
        {% comment %} <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button> {% endcomment %}
        {% comment %} <button type="button" class="btn btn-primary">Сохранить изменения</button> {% endcomment %}
      </div>
    </div>
  </div>
</div>
<!-- Модальное окно зависимости разделов и параметров -->
{% include 'cases/section_parameter_in_table.html' %}
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> ОК </button>
    </div>
  {% endfor %}
{% endif %}
</form>
<!-- <button type="button" class="btn btn-success">Сохранить</button> -->
{% endblock %}

Economy/project/templates/cases/case_list.html
{% extends 'base.html' %}

{% block title %} Кейсы {% endblock %}
{% load global_context %}
{% load static %}

{% block content %}
  {% if case_list %}
    {% for case in case_list %}
      <a href="{% url 'cases:case_view' case.Case_ID %}">{{case.Case_Name}}</a>  
      <br>    
    {% endfor%}
  {% else %}
    Кейсов нет
  {% endif %}
<!-- <button class="btn btn-primary" type="submit"> Добавить </button> -->
<br> 
<form action="{% url 'cases:case_add' %}"><button class="btn btn-primary">Создать новый кейс</button></form>
{% endblock %}

Economy/project/templates/cases/case_view.html
{% extends 'base.html' %}

{% block title %} {{case.Case_Name}} {% endblock %}
{% load global_context %}
{% load static %}

{% block content %}

<p class="font-weight-bold"> Название кейса: {{case.Case_Name}}</p>
<p><b>Комментарий: </b>{{case.Case_Comment}}</p>
<table>  
  {% include 'cases/tbody/thead.html' %} <!-- Вывод заголовока -->
  <tbody>
    {% if case.section_set.all %} 
      {% for section in case.section_set.all|sort:'Section_Sort' %}
        {% if not section|is_default_section %}
          <tr> <!-- Вывод Разделов как подзаголовков, кроме __default -->
            <th class="column-1">
              {% comment %} <a href="{% url 'cases:section_view' case.Case_ID section.Section_ID %}"> {% endcomment %}
                {{section.Section_Name}}
              {% comment %} </a>  {% endcomment %}
            </th>
          </tr> 
          {% include 'cases/tbody/tbody_section_view.html' %} <!-- Вывод тела таблицы для просмотра раздела --> 
        {% endif %}             
      {% endfor %}
    {% endif %} 
  </tbody>     
</table>
<br> 
<a class="btn btn-outline-success" href="{% url 'cases:case_edit' case.Case_ID %}">Изменить</a> 
{% endblock %}

Economy/project/templates/cases/case_view_all.html
{% extends 'base.html' %}

{% block title %} Кейсы {% endblock %}
{%load global_context%}
{% load static %}

{% block content %}

<div class="container" id="Analitical"  {%if not request.user|has_group:"Преподаватель" %} style="display: none;" {%endif%}>
  <div class="row">
    <div class="col-md-7">
      <div class="col-md-100" style="min-height:650px;">
    <table class="table table-striped">
      <!-- <thead class="thead-light">
        <th>Мои кейcы</th>
        <th></th>
        <th></th>
        {%if request.user|has_group:"Преподаватель" %}
        <th></th>
        {%endif%}
        {%if not request.user|has_group:"Преподаватель" %}
        <th><button class="btn btn-success" id="back" onclick="exit()" > Назад </button></th>
        {%endif%}
      </thead> -->
      <thead>
        <tr>
          <th>
            Название
          </th>
          <th>
            Коментарий
          </th>
          <th>
            
          </th>
          <!-- {%if request.user|has_group:"Преподаватель" %}
          <th>
            
          </th>
          {%endif%} -->
        </tr>
      </thead>
          <form method="POST" onsubmit="return confirm('Вы уверены в своем действии?');">
            {%csrf_token%}
      <tbody>

        {%for item in user.job_set.all%}
        <!-- {%if request.user|has_group:"Преподаватель" and item.User == request.user or not item.Job_Param.Case.Is_Pattern%} -->
        <tr>
        <td>
          {{item.Job_Param.Param_Name}}
        </td>
        <td>
          {{item.Job_Param.Param_Help}}
        </td>
        <td>
          <a href="{% url 'cases:detail' item.Job_Param.Case.id %}" class="top-menu">Просмотр<span class=" glyphicon glyphicon-pencil "></span></a>
        </td>
          <!-- {%if request.user|has_group:"Преподаватель" %} -->
            <td>
              <a href="{% url 'cases:edit' item.Job_Param.Case.id %}" class="top-menu">Редактирование</span></a>
            </td>
          <!-- {%endif%} -->
          <td>
          <!-- {%if not request.user|has_group:"Преподаватель" %} -->
            <!-- {%if item.Job_Param.Case.Is_Analitical%} -->
               <button type="submit" class="btn btn-danger" name ="{{item.Job_Param.Case.id}}"> X </button>
            <!-- {%endif%} -->
          <!-- {%endif%} -->
            </td>
        </tr>
        <!-- {%endif%} -->
        {%endfor%}
      </tbody>
    </form>
        </table>
      </div>
    </div>
    <div class="col-md-5 ">
      <div class="col-md-15">  
        <!-- {%if not request.user|has_group:"Преподаватель"%} -->
          <h3>
            Создать новую работу
          </h3>
        <!-- {%else%} -->
          <h3>
            Создать шаблон по существующему
          </h3>
        <!-- {%endif%} -->
          <!-- {%if request.user|has_group:"Преподаватель"%} -->
            <form method="POST" onsubmit="return confirm('Вы уверены в своем действии?');">
              {%csrf_token%}
              <div class="input-group mb-3">
              
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1">Выбрать шаблон:</span>
                </div>
                 <select name = "case" required="" class="custom-select my-0 mr-sm-0">
                  <optgroup data-name="district" label="Шаблоны преподавателей">
                    {%for job in Job_list%}
                      <!-- {%if job.Job_Param.Case.Is_Pattern and job.Job_Param.Case.Is_Ready%} -->
                        <option  value="{{job.Job_Param.Case.id}}" >
                          {{job.Job_Param.Case.Case_Name}}
                        </option>
                      <!-- {%endif%} -->
                    {%endfor%}
                  </optgroup>
                    <optgroup data-name="district" label="Шаблоны для преподавателей">
                      {%for job in Job_list%}
                      <!-- {%if job.Job_Param.Case.Is_Pattern_For_Teacher%} -->
                        <option  value="{{job.Job_Param.Case.id}}" >
                          {{job.Job_Param.Case.Case_Name}}
                        </option>
                      <!-- {%endif%} -->
                    {%endfor%}
                    </optgroup>
                    
                  </select>
              </div>
              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1">Название работы:</span>
                </div>
                 <input type="text" name="Job_Title" maxlength="100" required="" class="form-control" id="id_Case_Name" placeholder="Введите название">
              </div>

              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1"> Комментарий:</span>
                </div>
                    <input type="text" name="Job_Comment" maxlength="300" class="form-control" required="" id="id_Case_Comment" placeholder="Введите комментарий">
              </div>
              {%if not request.user|has_group:"Преподаватель"%}
              <div class ="form">
                <input  class="form-control" type="number" name="Period" id="Period0" placeholder="Дата" class="amount" min="1900" max="2020" required="">
                <input type="button" class = "add" title="Добавить ещё один объект типа " value="Добавить"></input >
              </div>
              {%endif%}
              <input class="btn btn-primary" type="submit" name="save" value="Создать из шаблона">
            </form>
          <!-- {%endif%} -->
          <br>
          <input class="btn btn-primary"  type="submit" name="create" value="Создать новый" OnClick="location.href='cases/createcase'"> 
          {%if not request.user|has_group:"Преподаватель"%}
          Для того чтобы начать работу со своим кейсом<br>
          Нажмите на кнопку "Перейти к созданию нового задания"
          <a class="btn btn-primary" href="{% url 'cases:CreateCaseWithPattern' %}">Перейти к созданию нового задания</a>
          {%endif%}
      </div>     
    </div>
    
  </div>
</div>

<!-- {%if not request.user|has_group:"Преподаватель" %}
<div class="container-fluid" id="block" >
  <div class="row">
    <div class="row justify-content-md-center">
    <b style="font-size: 400%">
      Оценка экономической безопасности компаний
    </b>
      
      <div style=" font-size:80%; justify-content: center;" >
        <label style="font-size: 18px; justify-content: center;">
          Для того чтобы начать работу вам нужно нажать кнопку "Обучающий модуль по оценке экономической безопасности компании на примере ПАО ЧТПЗ"<br>
          После того как преподаватель отметит вашу работу как выполненную, откроется доступ ко второй части "Аналитический модуль по оценке экономической безопасности  компании"<br>
         
        </label>
      </div>
      <div >
        {%if My_Jobs|GetCase:'ПАО ЧТПЗ'%}
          <button  onclick="location.href='{%url 'cases:detail' My_Jobs|GetCase:'ПАО ЧТПЗ'|GetId %}'" style="height: 200px;  width: 49%" class="btn btn-primary btn-lg ">
            <p style="font-size: 22px" ><label id="pink">Обучающий модуль по оценке экономической безопасности компании на примере ПАО ЧТПЗ</label></p> 
          </button>
        {%else%}
          <a  style="height: 200px;  width: 49%" class="btn btn-secondary btn-lg ">
            <label id="pink">Обучающий модуль по оценке экономической безопасности компании на примере ПАО ЧТПЗ</label>
          </a>
        {%endif%}

        {%if My_Jobs|GetCase:'ПАО ЧТПЗ'|Is_evaluated%}
          <button style="height: 200px;  width: 49%; font-size: 20px" onclick = "change()" class="btn btn-primary btn-lg">
            <label id="pink">Аналитический модуль по оценке экономической безопасности компании</label>
          </button>
        {%else%}
          <div title="Аналитическая часть недоступна..." style="height: 200px;  width: 49%; font-size: 20px" class="btn btn-secondary btn-lg">
            <label id="pink">Аналитический модуль по оценке экономической безопасности компании</label>
          </div>
        {%endif%}
      </div>
    </div>
  </div>
</div>
{%endif%} -->


<script type="text/javascript">
  
 var $add = document.getElementsByClassName('add')[0];
 var $form = document.getElementsByClassName('form')[0];
 x = 0;
$add.addEventListener('click', function(event) {
  date = new Date();

  if(x < 5 ){
  var $input = document.createElement('input');
  $input.type = 'number';
  $input.id = 'Period'+ x +'';
  $input.name = 'Period';
  $input.required = '';
  $input.placeholder = 'Дата';
  $input.classList.add('amount');
  $input.min = 1900;
  $input.classList.add("form-control");
  $input.max = date.getFullYear();
  $form.insertBefore($input, $add);
  x++;

}
});

  function change(){
    document.getElementById("block").style.display = 'none';
    document.getElementById("Analitical").style.display = 'block';
  }

  function exit(){
    document.getElementById("block").style.display = 'block';
    document.getElementById("Analitical").style.display = 'none';
  }

</script>

<style type="text/css">
  #pink{
text-shadow: 0 0 2px #fff, 
             -1px -1px 0 hsl(0, 0%, 0%),
             -2px -2px 1px hsl(0, 0%, 0%),
             -2px -2px 2px hsl(0, 0%, 0%);
  }
</style>

{% endblock %}


Economy/project/templates/cases/caseparam_view.html
{% extends 'base.html' %}

{% block title %} {{caseparam.Param_Name}} {% endblock %}
{% load static %}

{% block content %}

<h2>{{caseparam.Param_Name}}</h2>

{% if dateparam_list_in_caseparam %}
  {% for dateparam in dateparam_list_in_caseparam %}  
    {{dateparam.Param_Period}}
    {{dateparam.Param_Value}}
    <hr>
  {% endfor%}
{% else %}
    Параметров нет
{% endif %}

{% endblock %}

Economy/project/templates/cases/section_list.html
{% extends 'base.html' %}

{% block title %} Разделы {% endblock %}
{% load static %}

{% block content %}

  {% if section_list %}
    {% for section in section_list %}
      <a href="{% url 'cases:section_view' section.id%}">{{section.Section_Name}}</a>
    {% endfor%}
  {% else %}
    Разделов нет
  {% endif %}

{% endblock %}