Economy/project/apps/cases/urls.py
from django.urls import path, include

from .import views 

app_name = 'cases'
urlpatterns = [
    path('', views.case_list, name='case_list'),
    path('case_add/', views.case_add, name='case_add'),
    path('<int:case_id>/', views.case_view, name='case_view'),
    path('<int:case_id>/case_edit', views.case_edit, name='case_edit'),
    # path('<int:case_id>/period_add/', views.period_add, name='period_add'),
    # path('<int:case_id>/section_add/', views.section_add, name='section_add'),
    # path('<int:case_id>/parameter_add/', views.parameter_add, name='parameter_add'),
    # path('<int:case_id>/section_parameter/', views.section_parameter, name='section_parameter'),
    # path('<int:case_id>/section/<int:section_id>/', views.section_view, name='section_view'), 
    # path('<int:case_id>/section_edit/<int:section_id>/', views.section_edit, name='section_edit'),
]

Economy/project/apps/students/urls.py
from django.urls import path, include

from .import views 

app_name = 'students'
urlpatterns = [
    path('', views.case_list, name='case_list'),
    # path('case_add/', views.case_add, name='case_add'),
    # path('<int:case_id>/', views.case_view, name='case_view'),
    # path('<int:case_id>/case_edit', views.case_edit, name='case_edit'),
    # path('<int:case_id>/period_add/', views.period_add, name='period_add'),
    # path('<int:case_id>/section_add/', views.section_add, name='section_add'),
    # path('<int:case_id>/parameter_add/', views.parameter_add, name='parameter_add'),
    # path('<int:case_id>/section_parameter/', views.section_parameter, name='section_parameter'),
    # path('<int:case_id>/section/<int:section_id>/', views.section_view, name='section_view'), 
    # path('<int:case_id>/section_edit/<int:section_id>/', views.section_edit, name='section_edit'),
]

Economy/project/apps/teachers/urls.py
from django.urls import path, include

from .import views 

app_name = 'teachers'
urlpatterns = [
    path('', views.case_list, name='case_list'),
    # path('case_add/', views.case_add, name='case_add'),
    # path('<int:case_id>/', views.case_view, name='case_view'),
    # path('<int:case_id>/case_edit', views.case_edit, name='case_edit'),
    # path('<int:case_id>/period_add/', views.period_add, name='period_add'),
    # path('<int:case_id>/section_add/', views.section_add, name='section_add'),
    # path('<int:case_id>/parameter_add/', views.parameter_add, name='parameter_add'),
    # path('<int:case_id>/section_parameter/', views.section_parameter, name='section_parameter'),
    # path('<int:case_id>/section/<int:section_id>/', views.section_view, name='section_view'), 
    # path('<int:case_id>/section_edit/<int:section_id>/', views.section_edit, name='section_edit'),
]

Economy/project/apps/cases/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.contrib import messages
from .models import  Case, Section, Parameter, Period, Data, Formula, Variable, Job, Status
from .form import Create_Case_Form, Create_Period_Form, Create_Section_Form, Create_Parameter_Form, Edit_Case_Form, Edit_Section_Form

# Список всех кейсов
@login_required
def case_list(request):
    case_data = {
        'case_list': Case.objects.all(),
    }
    return render(request, 'cases/case_list.html', case_data )

# Создание нового кейса
@login_required
def case_add(request):
    if request.method == "POST":
        form = Create_Case_Form(request.POST)
        if form.is_valid():
            case = Case(
                Case_Name=form.cleaned_data['Case_Name'], 
                Case_Comment=form.cleaned_data['Case_Comment'])
            case.save()
            section_default_add(case) #При создании кейса создаем дефолтную секцию
            return redirect('cases:case_edit', case.Case_ID)
    form = Create_Case_Form()
    case_data = {
        'form': form,
    }
    return render(request, 'cases/case_add.html', case_data)

# Просмотр кейса
@login_required
def case_view(request, case_id):
    try: case = Case.objects.get(Case_ID = case_id)
    except: raise Http404("Кейс " + str(case_id) + " не найден")
    case_data = {
        'case': case,} 
    return render(request, 'cases/case_view.html', case_data)

# Редактирование кейса
@login_required
def case_edit(request, case_id):
    # try: case = Case.objects.get(Case_ID = case_id)
    # except: raise Http404("Кейс " + str(case_id) + " не найден")
    case = Case.objects.get(Case_ID = case_id)
    if request.method == "POST":
        case_save(request, case)
        form = Edit_Case_Form(request.POST, case_id)
        if request.POST.get("save_case"): #Сохранение
            return redirect('cases:case_edit', case.Case_ID)        
        elif request.POST.get("period_add"): #Добавление периода
            period_add_in_table(case)
            return redirect('cases:case_edit', case.Case_ID)
        elif request.POST.get("section_add"): #Добавление периода
            section_add_in_table(case)
            return redirect('cases:case_edit', case.Case_ID)
        elif request.POST.get("formula_calculate"): #Расчет формул
            formula_calc = formula_calculate(request, case)
            if formula_calc:
                messages.error(request, formula_calc)
            else: return redirect('cases:case_edit', case.Case_ID)
        else:
            for section in case.section_set.all(): #Добавление параметров
                if request.POST.get("parameter_add_in_" + str(section.Section_ID)):
                    parameter_add_in_table(case, section)
                    return redirect('cases:case_edit', case.Case_ID)
                    # setattr(section, "Section_Name", new_data)
            section_parameter_in_table(request, case)
            return redirect('cases:case_edit', case.Case_ID)
    form = Edit_Case_Form()
    case_data = {
        'case': case,
        'form': form,        
        'parameter_in_case': parameter_in_case(case),
        'section_in_case': case.section_set.all()
        }
    return render(request, 'cases/case_edit.html', case_data)

# Сохранение кейса
def case_save(request, case):
    case.Case_Name = request.POST.get("Case_" + str(case.Case_ID))
    case.Case_Comment = request.POST.get("Case_Comment_" + str(case.Case_ID))
    case.save()
    for section in case.section_set.all():
        if not section.Section_Name == "__default":
            section.Section_Name = request.POST.get("Section_" + str(section.Section_ID))
            section.save()
        for parameter in section.parameter_set.all():
            parameter_save(request, parameter, case)
    for period in case.period_set.all():
        period.Period_Name = request.POST.get("Period_" + str(period.Period_ID))
        period.save()

    # Исходные данные:
    # Перебор всех переменных
    # for i_var in range(0, len(Variable_Name)): 
        # if (Formula_Expression.find(Variable_Name[i_var]) != -1):  # Если переменная найдена
            # Formula_Expression = Formula_Expression.replace(Variable_Name[i_var], str(Variable[i_var])) # То перезаписываем ее на цифру - либо на ID 

    # Далее уже идет вычисление из строки
    # Formula_Expression.split() # Удаляем пробелы
    # Formula_Expression = Formula_Expression.replace("^", "**") # Заменяем степени

    # return eval(Formula_Expression) # Вычисляем строку

# Создание сеции по умолчанию
def section_default_add(case):
    section = Section(
        case = case,
        Section_Name = "__default",
        Section_Sort = sorting_weight_section(case))
    section.save()

# ID дефолтной секции
def default_section(case):
    for section in case.section_set.all():
        if section.Section_Name == "__default":
            return section.Section_ID

# Добавлние секции
def section_add_in_table(case):
    section = Section.objects.create(
        case = case,
        Section_Name = '',
        Section_Sort = sorting_weight_section(case))
    section.save()

# Добавлние секции
# def section_add(request, case_id):
#     case = Case.objects.get(Case_ID = case_id)
#     if request.method == "POST":        
#         form = Create_Section_Form(request.POST, case_id)
#         # if form.is_valid():
#         section = Section(
#             case = case,
#             Section_Name = request.POST.get("Section_"))
#         # section.case.add(case) #Создание связи с кейсом
#         section.save()
#         return redirect('cases:section_edit', case.Case_ID, section.Section_ID)
#     form = Create_Section_Form()
#     section_data = {
#         'form': form,
#         'case': case,
#     }
#     return render(request, 'cases/section_add.html', section_data)

# # Просмотр секции
# # def section_view(request, case_id, section_id):
#     case = Case.objects.get(Case_ID = case_id)   
#     section = Section.objects.get(Section_ID = section_id)
#     section_data = {
#         'case': case, 
#         'section': section,
#         }    
#     return render(request, 'cases/section_view.html', section_data)

# Редактирование секции
def section_edit(request, case_id, section_id):
    case = Case.objects.get(Case_ID = case_id)
    section = Section.objects.get(Section_ID = section_id)
    if request.method == "POST":
        form = Edit_Section_Form(request.POST, case_id, section_id)
        section.Section_Name = request.POST.get("Section_" + str(section.Section_ID))
        section.save(update_fields=['Section_Name'])
        for parameter in section.parameter_set.all():
            parameter_save(request, parameter, case)
    form = Edit_Section_Form()
    section_data = {
        'form': form,
        'case': case,
        'section': section,
    }
    return render(request, 'cases/section_edit.html', section_data)

# Редактирование связи парамеров и секций в таблице
def section_parameter_in_table(request, case):
    for parameter in parameter_in_case(case): #Перебираем по очереди все параметры в кейсе
        for section in case.section_set.all(): #Перебираем все секции в кейсе, для проверки связи
            if not section.Section_Name == "__default":
                if request.POST.get(str(section.Section_ID) + "_" + str(parameter.Parameter_ID), None):
                    parameter.section.add(section)
                    parameter.save()
                elif parameter.section.filter(Section_ID = section.Section_ID).count(): # Проверка связи параметра с разделом
                    parameter.section.remove(section)
                    parameter.save()

# Редактирование связи парамеров и секций
# def section_parameter(request, case_id): 
#     case = Case.objects.get(Case_ID = case_id)
#     if request.method == "POST":
#         for parameter in parameter_in_case(case): #Перебираем по очереди все параметры в кейсе
#             for section in case.section_set.all(): #Перебираем все секции в кейсе, для проверки связи
#                 if not section.Section_Name == "__default":
#                     if request.POST.get(str(section.Section_ID) + "_" + str(parameter.Parameter_ID), None):
#                         parameter.section.add(section)
#                         parameter.save()
#                     elif parameter.section.filter(Section_ID = section.Section_ID).count(): # Проверка связи параметра с разделом
#                         parameter.section.remove(section)
#                         parameter.save()
#         return redirect('cases:section_parameter', case.Case_ID)
#     section_parameter_data = {
#         'case': case,
#         'parameter_in_case': parameter_in_case(case),
#         'section_in_case': case.section_set.all()
#     }
#     return render(request, 'cases/section_parameter.html', section_parameter_data) 

# Вывод всех параметров в кейсе
def parameter_in_case(case):
    return Section.objects.get(Section_ID = default_section(case)).parameter_set.all()

# Добавление параметра в таблице
def parameter_add_in_table(case, section):
    parameter = Parameter.objects.create(
        Parameter_Name = '', 
        Parameter_Comment = '',
        Parameter_Sort = sorting_weight_parameters(case))
    parameter.section.add(section) #Создание связи с секцией
    parameter.section.add(Section.objects.get(Section_ID = default_section(case)))
    parameter.save()
    variable = Variable(
        parameter = parameter, 
        Variable_Name = '')
    variable.save()
    formula = Formula(
        parameter = parameter,

Economy/project/apps/students/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.contrib import messages
from cases.models import  Case, Section, Parameter, Period, Data, Formula, Variable, Job, Status
from cases.form import Create_Case_Form, Create_Period_Form, Create_Section_Form, Create_Parameter_Form, Edit_Case_Form, Edit_Section_Form

# Список всех кейсов
@login_required
def case_list(request):
    return render(request, 'cases/case_list.html', {'case_list': Case.objects.all()})

Economy/project/apps/teachers/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.contrib import messages
from cases.models import  Case, Section, Parameter, Period, Data, Formula, Variable, Job, Status
from cases.form import Create_Case_Form, Create_Period_Form, Create_Section_Form, Create_Parameter_Form, Edit_Case_Form, Edit_Section_Form

# Список всех кейсов
@login_required
def case_list(request):
    # if request.user.groups.filter(name='Students').exists():
    user = request.user
    job = Job.objects.all()
    case_list = Case.objects.all()
    # user.job.case.all()
    # Case.objects.all()
        # return redirect('students:case_list')
    # elif request.user.is_superuser:
        # return redirect('admin/')
    # elif request.user.groups.filter(name='Teachers').exists():
        # return redirect('teachers:case_list')
    # else:
        # return redirect('login/')
    case_data = {
        'case_list': case_list,
        'users': user,
        'job': job,
    }
    return render(request, 'cases/case_list.html', case_data )

Economy/project/templates/base.html
<!DOCTYPE html>
<html>
{% load global_context %}
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} Кейсы {% endblock %}</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="icon" href="https://www.susu.ru/sites/default/files/favicon_0.ico" type="image/x-icon">
  <style type="text/css">
  #box {
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    z-index: 999;
    display: none;
  }
  #content {
    width: 500px; /* Ширина слоя */
    margin: 0 auto 50px; /* Выравнивание по центру */
  }
  #footer {
    position: fixed; /* Фиксированное положение */
    left: 0; bottom: 0; /* Левый нижний угол */
    padding: 10px; /* Поля вокруг текста */
    background: #39b54a; /* Цвет фона */
    color: #fff; /* Цвет текста */
    width: 100%; /* Ширина слоя */
  }
  #box-inner {
    position: absolute;
    left: 0px;
    right: 0px;
    top: 0px;
    bottom: 0px;
    background: blue;
    opacity: 0.3;
    display: none;
  }
  #box #container {
    position: absolute;
    top: 0; bottom: 0; right: 0; left: 0; /* центрирование */
    margin: auto;  /* центрирование */
    height: 15em;
    width: 25em;
    border: 1px solid black;
    background: white;
    padding: 1%; 
  }
  iframe {
    width: 100%;
    height: 100%;
    border: none;
  }
  </style>
</head>

<body style="background: rgba(0, 0, 0, 0) url(https://www.toptal.com/designers/subtlepatterns/patterns/double-bubble-outline.png) repeat scroll 0% 0%;">    
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <img width="25%" href="{% url 'cases:case_list' %}" height="25%" src="https://www.susu.ru/sites/all/themes/boot2017/logo/ru/wider/2400.png">   
      <!-- <h4 class="my-0 col-md-3 md-mr-auto font-weight-normal">Высшая школа экономики и управления </h4> -->
      <nav class="my-2 my-md-0 mr-md-3">
        
        <!-- {%if request.user|has_group:"Преподаватель" %} -->
        <!-- <a class="p-2 text-dark" href="{%url 'cases:students' %}">Задания студентов</a>  -->
        <!-- <a class="p-2 text-dark" href="{% url 'cases:create' %}">Управление шаблонами</a> -->
        <!-- <a class= "p-2 text-dark" href ="{% url 'cases:files' %}">Файлы</a> -->
        <!-- {%endif%} -->
        {%if not request.user|has_group:"Преподаватель" and user.is_superuser %}
          <a class="p-2 text-dark" href="{% url 'cases:case_list' %}">Кейсы</a>
          <a class= "p-2 text-dark" href ="/admin"><b>Перейти в админку</b></a>
        {%endif%}
      </nav>
      <!-- Авторизация -->
      {% if user.is_authenticated %}
        <a class="p-2 text-dark"> Здравствуйте, 
          {{ users.first_name }}
          {{ job }}
        </a>
        {% comment %} <a class="btn btn-outline-primary" href="{% url 'logout'%}?next={{request.path}}">Выйти</a>  {% endcomment %}
        <a class="btn btn-outline-primary" href="{% url 'logout'%}">Выйти</a> 
      {% else %}
        <a class="btn btn-outline-primary" href="{% url 'login'%}">Войти</a> 
        {% comment %} <a class="btn btn-outline-primary" href="{% url 'login'%}?next={{request.path}}">Войти</a>  {% endcomment %}
      {% endif %} 
  </div>
  <div style="min-height:650px;">
    {% block content %}{% endblock %}
    <style>  
    /* Стили используемые в шаблонах */
      .column { 
        text-align: center;
      }
      .form-control{
        border:none;
      }
      td {
        padding: 1px;
        padding-right: 10px;
        border: 1px solid lightgray;
      }
      th {
        padding: 1px;
      }
    </style>
  </div>

  <footer style=" bottom:0; ">
    <div style='background: rgba(10, 10, 100, 0) url("https://www.toptal.com/designers/subtlepatterns/patterns/double-bubble-outline.png") repeat scroll 0% 11%;' style="margin-left: 50px;">
      <hr />
      <p>Россия, 454080 <a href="https://www.susu.ru/ru/about/campus" title="Карта">Челябинск, проспект Ленина, 76</a><br>
        Тел./факс: +7 (351) 267-99-00<br>
        E-mail: <a href="mailto:info@susu.ru" processed="processed">info@susu.ru</a><br>
        Центр информации и связей с общественностью: <a href="mailto:press@susu.ru" processed="processed">press@susu.ru</a><br>
        Техподдержка сайта: <a href="mailto:support@susu.ru" processed="processed">support@susu.ru</a></p>
    </div>
  </footer>
</body>
</html>