Economy-nikita/project/apps/cases/urls.py
from django.urls import path, include

from .import views 

app_name = 'cases'
urlpatterns = [
    path('', views.case_list, name='case_list'),    
    path('case_add/', views.case_add, name='case_add'),
    path('<int:case_id>/', views.case_view, name='case_view'),
    path('<int:case_id>/case_edit', views.case_edit, name='case_edit'),     
    path('<int:case_id>/period_add/', views.period_add, name='period_add'),   
    path('<int:case_id>/section_add/', views.section_add, name='section_add'),    
    path('<int:case_id>/parameter_add/', views.parameter_add, name='parameter_add'),
    path('<int:case_id>/section/<int:section_id>/', views.section_view, name='section_view'),    
    path('<int:case_id>/section_edit/<int:section_id>/', views.section_edit, name='section_edit'),    
]

Economy-nikita/project/apps/cases/models.py
from django.db import models
# from django.contrib.auth.models import User
# from django.db.models import Q
# import datetime

# Модели: Case, Section, Parameter, Period, Data

# Модель Кейс - это самая главная модель которая содержит в себе все параметры, работы, файлы, и т.д
class Case(models.Model):
    Case_ID = models.AutoField(primary_key=True)
    Case_Name = models.CharField('Название кейса', max_length=50)
    Case_Comment = models.TextField('Коментарий')
    Case_Parent = models.IntegerField('Родительский кейс', default=-1)
    Image = models.FileField(upload_to= 'uploads/product_images/', blank=True, null=True)

    def __str__(self):
        return self.Case_Name

    def get_absolute_url(self):  # Отвечает за ссылку 'Смотреть на сайте' - переход от админки на сайт
        return f'/cases/{self.Case_ID}/'

    class Meta:
        verbose_name = 'Кейс'
        verbose_name_plural = 'Кейсы'


# Раздел кейса, нужен для того чтобы обозначать имена разделов, если такие понадобятся
# Содержит в себе параметры
class Section(models.Model):    
    Section_ID = models.AutoField(primary_key=True)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    Section_Name = models.CharField('Название раздела', max_length=100)

    def __str__(self):
        return self.Section_Name

    def get_absolute_url(self):  # Отвечает за ссылку 'Смотреть на сайте' - переход от админки на сайт
        return f'/cases/section/{self.Section_ID}/'

    class Meta:
        verbose_name = 'Раздел кейса'
        verbose_name_plural = 'Разделы кейса'


# Параметр кейса, нужен для того чтобы отображать имя, комментарий
class Parameter(models.Model): # Бывший CaseParam
    Parameter_ID = models.AutoField(primary_key=True)
    section = models.ManyToManyField(Section) # Cвязь многие ко многим
    Parameter_Name = models.CharField('Название', max_length=100)
    Parameter_Comment = models.TextField('Коментарий')
    Parameter_Sort = models.FloatField('Вес при сортировке', default=Parameter_ID, null=True) # По умолчанию равен ID - то есть в порядке создания
    # Parameter_Var = models.CharField('Название переменной', max_length=100) отделяем название переменной, как отдельную сущноть

    def __str__(self):
        return self.Parameter_Name

    class Meta:
        verbose_name = 'Параметр'
        verbose_name_plural = 'Параметры'


# Период сбора данных - периоды в промежутках которых были собранны данные
class Period(models.Model):
    Period_ID = models.AutoField(primary_key=True)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    Period_Name = models.CharField('Период', max_length=100)
    Period_Sort = models.FloatField('Вес при сортировке', default=Period_ID, null=True) # По умолчанию равен ID - то есть в порядке создания
    
    def __str__(self):
        return self.Period_Name

    class Meta:
        verbose_name = 'Период'
        verbose_name_plural = 'Периоды'


# Данные - значения параметра за определенный период
class Data(models.Model):
    parameter = models.ForeignKey(Parameter, on_delete=models.CASCADE)
    period = models.ForeignKey(Period, on_delete=models.CASCADE)    
    Data_ID = models.AutoField(primary_key=True)
    Data_Value = models.FloatField('Значение', default=0, null=True, blank=True)
    
    def __str__(self):
        return str(self.Data_Value)

    class Meta:
        verbose_name = 'Значение'
        verbose_name_plural = 'Значения'
        

# Переменные
class Variable(models.Model):
    Variable_ID = models.AutoField(primary_key=True)
    parameter = models.OneToOneField(Parameter, on_delete=models.CASCADE)
    Variable_Name = models.CharField('Переменная', max_length= 100)

    def __str__(self):
        return self.Variable_Name

    class Meta:
        verbose_name = 'Переменная'
        verbose_name_plural = 'Переменные'


# Формулы - модель для связи формулы с Переменными
class Formula(models.Model):
    Formula_ID = models.AutoField(primary_key=True)
    parameter = models.OneToOneField(Parameter, on_delete=models.CASCADE)    
    variable = models.ManyToManyField(Variable) # Cвязь многие ко многим
    Formula_Name = models.CharField('Формула', max_length= 100)

    def __str__(self):
        return self.Formula_Name
    
    class Meta:
        verbose_name = 'Формула'
        verbose_name_plural = 'Формулы'

Economy-nikita/project/apps/cases/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from .models import  Case, Section, Parameter, Period, Data, Formula, Variable
from .form import Create_Case_Form, Create_Period_Form, Create_Section_Form, Create_Parameter_Form, Edit_Case_Form, Edit_Section_Form
from  django.shortcuts import render
from .form import UploadFileForm

# Список всех кейсов
def case_list(request):
    return render(request, 'cases/case_list.html', {'case_list': Case.objects.all()})

# Создание нового кейса
def case_add(request):
    if request.method == "POST":
        form = Create_Case_Form(request.POST)
        if form.is_valid():
            case = Case(
                Case_Name=form.cleaned_data['Case_Name'], 
                Case_Comment=form.cleaned_data['Case_Comment'])
            case.save()
            section_default_add(case) #При создании кейса создаем дефолтную секцию
            return redirect('cases:case_edit', case.Case_ID)
    form = Create_Case_Form()
    case_data = {
        'form': form,
    }
    return render(request, 'cases/case_add.html', case_data)

# Просмотр кейса
def case_view(request, case_id):
    try: case = Case.objects.get(Case_ID = case_id)
    except: raise Http404("Кейс " + str(case_id) + " не найден")
    case_data = {
        'case': case,
        'section_line_in_case': case.section_set.all()} 
    return render(request, 'cases/case_view.html', case_data)

# Редактирование кейса
def case_edit(request, case_id):
    try: case = Case.objects.get(Case_ID = case_id)
    except: raise Http404("Кейс " + str(case_id) + " не найден")    
    if request.method == "POST":
        if request.POST.get("save_case"):
            form = Edit_Case_Form(request.POST, case_id)
            case.Case_Name = request.POST.get("Case_" + str(case.Case_ID))
            case.Case_Comment = request.POST.get("Case_Comment_" + str(case.Case_ID))
            case.save()
            for section in case.section_set.all():
                for parameter in section.parameter_set.all():
                    save_parameter(request, parameter, case)
            return redirect('cases:case_view', case.Case_ID)
        elif request.POST.get("parameter_add"):
            section = Section.objects.get(Section_ID = default_section(case))
            parameter_add_in_table(case, section)
            return redirect('cases:case_edit', case.Case_ID)
        elif request.POST.get("period_add"):
            period_add_in_table(case)
            return redirect('cases:case_edit', case.Case_ID)        
    form = Edit_Case_Form()
    case_data = {
        'case': case,
        'form': form,
        } 
    return render(request, 'cases/case_edit.html', case_data)

        
    # Исходные данные:
    # Перебор всех переменных
    # for i_var in range(0, len(Variable_Name)): 
        # if (Formula_Expression.find(Variable_Name[i_var]) != -1):  # Если переменная найдена
            # Formula_Expression = Formula_Expression.replace(Variable_Name[i_var], str(Variable[i_var])) # То перезаписываем ее на цифру - либо на ID 

    # Далее уже идет вычисление из строки
    # Formula_Expression.split() # Удаляем пробелы
    # Formula_Expression = Formula_Expression.replace("^", "**") # Заменяем степени

    # return eval(Formula_Expression) # Вычисляем строку

# Добавление периода
def period_add(request, case_id):
    case = Case.objects.get(Case_ID = case_id)
    if request.method == "POST":        
        form = Create_Period_Form(request.POST, case_id)
        period = Period(
            case = case,
            Period_Name = request.POST.get("Period_"),
            Period_Sort = sorting_weight_periods(case))
        period.save()
        return redirect('cases:case_edit', case.Case_ID)
    form = Create_Period_Form()
    period_data = {
        'form': form,
        'case': case,
    }
    return render(request, 'cases/period_add.html', period_data)

# Создание сеции по умолчанию
def section_default_add(case):
    section = Section(
        case = case,
        Section_Name = "__default" )#+ str(case.Case_ID))
    section.save()

# ID дефолтной секции
def default_section(case):
    for section in case.section_set.all():
        if section.Section_Name == "__default":
            return section.Section_ID

# Добавлние секции
def section_add(request, case_id):
    case = Case.objects.get(Case_ID = case_id)
    if request.method == "POST":        
        form = Create_Section_Form(request.POST, case_id)
        # if form.is_valid():
        section = Section(
            case = case,
            Section_Name = request.POST.get("Section_"))
        # section.case.add(case) #Создание связи с кейсомв
        section.save()
        return redirect('cases:section_edit', case.Case_ID, section.Section_ID)
    form = Create_Section_Form()
    section_data = {
        'form': form,
        'case': case,
    }
    return render(request, 'cases/section_add.html', section_data)

# Просмотр секции
def section_view(request, case_id, section_id):
    case = Case.objects.get(Case_ID = case_id)   
    section = Section.objects.get(Section_ID = section_id)
    section_data = {
        'case': case, 
        'section': section,
        }    
    return render(request, 'cases/section_view.html', section_data)

# Редактирование секции
def section_edit(request, case_id, section_id):
    case = Case.objects.get(Case_ID = case_id)
    section = Section.objects.get(Section_ID = section_id)
    if request.method == "POST":
        form = Edit_Section_Form(request.POST, case_id, section_id)
        section.Section_Name = request.POST.get("Section_" + str(section.Section_ID))
        section.save()
        for parameter in section.parameter_set.all():
            save_parameter(request, parameter, case)
    form = Edit_Section_Form()
    section_data = {
        'form': form,
        'case': case,
        'section': section,
    }
    return render(request, 'cases/section_edit.html', section_data)

# Добавление параметра
def parameter_add(request, case_id):
    case = Case.objects.get(Case_ID = case_id)
    section = Section.objects.get(Section_ID = default_section(case))
    if request.method == "POST":
        form = Create_Parameter_Form(request.POST)
        parameter = Parameter.objects.create(
            Parameter_Name = request.POST.get("Parameter_"), 
            Parameter_Comment = '', 
            Parameter_Sort = sorting_weight_parameters(section))
        parameter.section.add(section) #Создание связи с секцией
        parameter.save()
        variable = Variable(
            parameter = parameter, 
            Variable_Name = request.POST.get("Variable_"))
        variable.save()
        formula = Formula(
            parameter = parameter,
            Formula_Name = request.POST.get("Formula_"))
        formula.save()
        for period in case.period_set.all():
            data_value = request.POST.get("Data_" + str(period.Period_ID))
            if not data_value:
                data_value = None
            data = Data(
                parameter = parameter,
                period = period,
                Data_Value = data_value)
            data.save()
        return redirect('cases:case_edit', case.Case_ID)
    form = Create_Parameter_Form()
    parameter_data = {
        'form': form,
        'case': case,
        'section': section}
    return render(request, 'cases/parameter_add.html', parameter_data)

# Установка веса для сортировки параметров
def sorting_weight_parameters(section):
    parameters = section.parameter_set.all()
    return (parameters.count() + 1) * 10

# Установка веса для сортировки периодов
def sorting_weight_periods(case):
    periods = case.period_set.all()
    return (periods.count() + 1) * 10

# Добавление параметра в таблице
def parameter_add_in_table(case, section):
    parameter = Parameter.objects.create(
        Parameter_Name = '', 
        Parameter_Comment = '',
        Parameter_Sort = sorting_weight_parameters(section))
    parameter.section.add(section) #Создание связи с секцией
    parameter.save()
    variable = Variable(
        parameter = parameter, 
        Variable_Name = '')
    variable.save()
    formula = Formula(
        parameter = parameter,
        Formula_Name = '')
    formula.save()
    for period in case.period_set.all():
        data = Data(
            parameter = parameter,
            period = period,
            Data_Value = None)
        data.save()

# Добавление периода в таблице
def period_add_in_table(case):
        period = Period(
            case = case,
            Period_Name = '',
            Period_Sort = sorting_weight_periods(case))
        period.save()

# Сохранение параметра
def save_parameter(request, parameter, case):
    parameter.Parameter_Name = request.POST.get("Parameter_" + str(parameter.Parameter_ID))
    parameter.save()
    parameter.variable.Variable_Name = request.POST.get("Variable_" + str(parameter.variable.Variable_ID)) 
    parameter.variable.save()
    parameter.formula.Formula_Name = request.POST.get("Formula_" + str(parameter.formula.Formula_ID)) 
    parameter.formula.save()
    for period in case.period_set.all(): 
        for data in parameter.data_set.all():
            if data.period.Period_ID == period.Period_ID and request.POST.get("Data_" + str(data.Data_ID)):
                data.Data_Value = request.POST.get("Data_" + str(data.Data_ID)) 
                data.save()

def page(request):
    form = UploadFileForm()
    return render(request, "page.html", {"form": form})

def page(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        save_path = '/uploads/product_images/' # папка для сохранения файлов
        if form.is_valid():
            # сохранение файла
            with open(save_path+request.FILES['file'].name, 'wb+') as destination:
                for chunk in request.FILES['file'].chunks():

Economy-nikita/project/templates/cases/case_add.html
{% extends 'base.html' %}

{% block title %} Создание нового кейса {% endblock %}
{% load static %}

{% block content %}

<div class="container">
  <h2> Формирование кейса </h2>  
  <div class="row justify-content-md-cente border">
      <div class="container">
        <div class="row justify-content-md-center">
          <div class="container-fluid">
            <form method="POST">
              {%csrf_token%}
              <br>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="">Название кейса:</span>
                </div>
                <input 
                class="form-control"  
                type="text" 
                name="Case_Name" 
                maxlength="500" 
                required=""
                >
              </div>
              <br>
              <div class="input-group">
                <textarea 
                  class="form-control"  
                  name="Case_Comment" 
                  maxlength="300" 
                  required="" 
                  id="id_Case_Comment"></textarea>
              </div>
              <br>
              <button type="submit" class="btn btn-primary">Создать</button>
              <input type="button" class="btn btn-primary" onclick="history.back();" value="Отмена"/>
              <br>
            </form>
          </div>
        </div>
      </div>
  </div>
</div>
{% endblock %}

Economy-nikita/project/templates/cases/case_edit.html
{% extends 'base.html' %}

{% block title %} {{case.Case_Name}} {% endblock %}
{% load global_context %}
{% load static %}

{% block content %}
<form method="POST">
  {%csrf_token%}
  <p class="font-weight-bold"> Название раздела:
    <!-- {{form.Section_Name}} -->
    <input
      class="form-control" 
      type="text"
      name="Case_{{case.Case_ID}}"
      value="{{case.Case_Name}}"
    >
  </p>
  <p class="font-weight-bold">    
    <b> 
      Комментарий:
    </b>
    <!-- {{form.Section_Name}} -->
    <input
      class="form-control" 
      type="text"
      name="Case_Comment_{{case.Case_ID}}"
      value="{{case.Case_Comment}}"
    >
  </p>
  <table>  
    {% include 'cases/thead_edit.html' %} <!-- Вывод заголовока -->    
    <tbody>    
      {% if case.section_set.all %} 
        {% for section in case.section_set.all %}             
          <tr> <!-- Вывод Разделов как подзаголовков -->
            <th class="column-1">
                {{section.Section_Name}}
              <!-- Изменене раздела -->
                <a class="btn btn-outline-success" href="{% url 'cases:section_edit' case.Case_ID section.Section_ID %}">              
                  &#9997
                </a>
            </th>
            <th class="column-1">
            </th>
          </tr>
          {% include 'cases/tbody_section_edit.html' %} <!-- Вывод заголовока -->
          <tr>
            <td>
              <input class="btn btn-primary" type="submit" name="parameter_add" value="Добавить параметр">
            </td>
          </tr>
        {% endfor %}

      {% endif %}
      <tr>
        <td>
          <a class="btn btn-primary" href="{% url 'cases:section_add' case.Case_ID %}">
            Добавить раздел
          </a>
        </td>
      </tr>
    </tbody>
  </table>
  <input class="btn btn-success" type="submit" name="save_case" value="Сохранить">
</form>

<!-- <button type="button" class="btn btn-success">Сохранить</button> -->
{% endblock %}

Economy-nikita/project/templates/cases/case_view.html
{% extends 'base.html' %}

{% block title %} {{case.Case_Name}} {% endblock %}
{% load global_context %}
{% load static %}

{% block content %}

<p class="font-weight-bold"> Название кейса: {{case.Case_Name}}</p>
<p><b>Комментарий: </b>{{case.Case_Comment}}</p>
<table>  
  {% include 'cases/thead.html' %} <!-- Вывод заголовока -->
  <tbody>
    {% if section_line_in_case %} 
      {% for section in section_line_in_case %}
        {% if not section.Section_Name == "__default" %}   
          <tr> <!-- Вывод Разделов как подзаголовков, кроме __default -->
            <th class="column-1">
              <a href="{% url 'cases:section_view' case.Case_ID section.Section_ID %}">
                {{section.Section_Name}}
              </a> 
            </th>
          </tr>
        {% endif %}    
        {% include 'cases/tbody_section_view.html' %} <!-- Вывод тела таблицы для просмотра раздела -->           
      {% endfor %}
    {% endif %} 
  </tbody>     
</table>
<br>
<form action="{% url 'cases:case_edit' case.Case_ID %}"><button class="btn btn-primary">Изменить</button></form>   
<br>
<input class="btn btn-primary" type="file" name="Image" id="id_Image">
<br>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form }}
  <input type="submit">
</form>
{% endblock %}

Economy-nikita/project/templates/cases/case_view_all.html
{% extends 'base.html' %}

{% block title %} Кейсы {% endblock %}
{%load global_context%}
{% load static %}

{% block content %}

<div class="container" id="Analitical"  {%if not request.user|has_group:"Преподаватель" %} style="display: none;" {%endif%}>
  <div class="row">
    <div class="col-md-7">
      <div class="col-md-100" style="min-height:650px;">
    <table class="table table-striped">
      <!-- <thead class="thead-light">
        <th>Мои кейcы</th>
        <th></th>
        <th></th>
        {%if request.user|has_group:"Преподаватель" %}
        <th></th>
        {%endif%}
        {%if not request.user|has_group:"Преподаватель" %}
        <th><button class="btn btn-success" id="back" onclick="exit()" > Назад </button></th>
        {%endif%}
      </thead> -->
      <thead>
        <tr>
          <th>
            Название
          </th>
          <th>
            Коментарий
          </th>
          <th>
            
          </th>
          <!-- {%if request.user|has_group:"Преподаватель" %}
          <th>
            
          </th>
          {%endif%} -->
        </tr>
      </thead>
          <form method="POST" onsubmit="return confirm('Вы уверены в своем действии?');">
            {%csrf_token%}
      <tbody>

        {%for item in user.job_set.all%}
        <!-- {%if request.user|has_group:"Преподаватель" and item.User == request.user or not item.Job_Param.Case.Is_Pattern%} -->
        <tr>
        <td>
          {{item.Job_Param.Param_Name}}
        </td>
        <td>
          {{item.Job_Param.Param_Help}}
        </td>
        <td>
          <a href="{% url 'cases:detail' item.Job_Param.Case.id %}" class="top-menu">Просмотр<span class=" glyphicon glyphicon-pencil "></span></a>
        </td>
          <!-- {%if request.user|has_group:"Преподаватель" %} -->
            <td>
              <a href="{% url 'cases:edit' item.Job_Param.Case.id %}" class="top-menu">Редактирование</span></a>
            </td>
          <!-- {%endif%} -->
          <td>
          <!-- {%if not request.user|has_group:"Преподаватель" %} -->
            <!-- {%if item.Job_Param.Case.Is_Analitical%} -->
               <button type="submit" class="btn btn-danger" name ="{{item.Job_Param.Case.id}}"> X </button>
            <!-- {%endif%} -->
          <!-- {%endif%} -->
            </td>
        </tr>
        <!-- {%endif%} -->
        {%endfor%}
      </tbody>
    </form>
        </table>
      </div>
    </div>
    <div class="col-md-5 ">
      <div class="col-md-15">  
        <!-- {%if not request.user|has_group:"Преподаватель"%} -->
          <h3>
            Создать новую работу
          </h3>
        <!-- {%else%} -->
          <h3>
            Создать шаблон по существующему
          </h3>
        <!-- {%endif%} -->
          <!-- {%if request.user|has_group:"Преподаватель"%} -->
            <form method="POST" onsubmit="return confirm('Вы уверены в своем действии?');">
              {%csrf_token%}
              <div class="input-group mb-3">
              
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1">Выбрать шаблон:</span>
                </div>
                 <select name = "case" required="" class="custom-select my-0 mr-sm-0">
                  <optgroup data-name="district" label="Шаблоны преподавателей">
                    {%for job in Job_list%}
                      <!-- {%if job.Job_Param.Case.Is_Pattern and job.Job_Param.Case.Is_Ready%} -->
                        <option  value="{{job.Job_Param.Case.id}}" >
                          {{job.Job_Param.Case.Case_Name}}
                        </option>
                      <!-- {%endif%} -->
                    {%endfor%}
                  </optgroup>
                    <optgroup data-name="district" label="Шаблоны для преподавателей">
                      {%for job in Job_list%}
                      <!-- {%if job.Job_Param.Case.Is_Pattern_For_Teacher%} -->
                        <option  value="{{job.Job_Param.Case.id}}" >
                          {{job.Job_Param.Case.Case_Name}}
                        </option>
                      <!-- {%endif%} -->
                    {%endfor%}
                    </optgroup>
                    
                  </select>
              </div>
              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1">Название работы:</span>
                </div>
                 <input type="text" name="Job_Title" maxlength="100" required="" class="form-control" id="id_Case_Name" placeholder="Введите название">
              </div>

              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1"> Комментарий:</span>
                </div>
                    <input type="text" name="Job_Comment" maxlength="300" class="form-control" required="" id="id_Case_Comment" placeholder="Введите комментарий">
              </div>
              {%if not request.user|has_group:"Преподаватель"%}
              <div class ="form">
                <input  class="form-control" type="number" name="Period" id="Period0" placeholder="Дата" class="amount" min="1900" max="2020" required="">
                <input type="button" class = "add" title="Добавить ещё один объект типа " value="Добавить"></input >
              </div>
              {%endif%}
              <input class="btn btn-primary" type="submit" name="save" value="Создать из шаблона">
            </form>
          <!-- {%endif%} -->
          <br>
          <input class="btn btn-primary"  type="submit" name="create" value="Создать новый" OnClick="location.href='cases/createcase'"> 
          {%if not request.user|has_group:"Преподаватель"%}
          Для того чтобы начать работу со своим кейсом<br>
          Нажмите на кнопку "Перейти к созданию нового задания"
          <a class="btn btn-primary" href="{% url 'cases:CreateCaseWithPattern' %}">Перейти к созданию нового задания</a>
          {%endif%}
      </div>     
    </div>
    
  </div>
</div>

<!-- {%if not request.user|has_group:"Преподаватель" %}
<div class="container-fluid" id="block" >
  <div class="row">
    <div class="row justify-content-md-center">
    <b style="font-size: 400%">
      Оценка экономической безопасности компаний
    </b>
      
      <div style=" font-size:80%; justify-content: center;" >
        <label style="font-size: 18px; justify-content: center;">
          Для того чтобы начать работу вам нужно нажать кнопку "Обучающий модуль по оценке экономической безопасности компании на примере ПАО ЧТПЗ"<br>
          После того как преподаватель отметит вашу работу как выполненную, откроется доступ ко второй части "Аналитический модуль по оценке экономической безопасности  компании"<br>
         
        </label>
      </div>
      <div >
        {%if My_Jobs|GetCase:'ПАО ЧТПЗ'%}
          <button  onclick="location.href='{%url 'cases:detail' My_Jobs|GetCase:'ПАО ЧТПЗ'|GetId %}'" style="height: 200px;  width: 49%" class="btn btn-primary btn-lg ">
            <p style="font-size: 22px" ><label id="pink">Обучающий модуль по оценке экономической безопасности компании на примере ПАО ЧТПЗ</label></p> 
          </button>
        {%else%}
          <a  style="height: 200px;  width: 49%" class="btn btn-secondary btn-lg ">
            <label id="pink">Обучающий модуль по оценке экономической безопасности компании на примере ПАО ЧТПЗ</label>
          </a>
        {%endif%}

        {%if My_Jobs|GetCase:'ПАО ЧТПЗ'|Is_evaluated%}
          <button style="height: 200px;  width: 49%; font-size: 20px" onclick = "change()" class="btn btn-primary btn-lg">
            <label id="pink">Аналитический модуль по оценке экономической безопасности компании</label>
          </button>
        {%else%}
          <div title="Аналитическая часть недоступна..." style="height: 200px;  width: 49%; font-size: 20px" class="btn btn-secondary btn-lg">
            <label id="pink">Аналитический модуль по оценке экономической безопасности компании</label>
          </div>
        {%endif%}
      </div>
    </div>
  </div>
</div>
{%endif%} -->


<script type="text/javascript">
  
 var $add = document.getElementsByClassName('add')[0];
 var $form = document.getElementsByClassName('form')[0];
 x = 0;
$add.addEventListener('click', function(event) {
  date = new Date();

  if(x < 5 ){
  var $input = document.createElement('input');
  $input.type = 'number';
  $input.id = 'Period'+ x +'';
  $input.name = 'Period';
  $input.required = '';
  $input.placeholder = 'Дата';
  $input.classList.add('amount');
  $input.min = 1900;
  $input.classList.add("form-control");
  $input.max = date.getFullYear();
  $form.insertBefore($input, $add);
  x++;

}
});

  function change(){
    document.getElementById("block").style.display = 'none';
    document.getElementById("Analitical").style.display = 'block';
  }

  function exit(){
    document.getElementById("block").style.display = 'block';
    document.getElementById("Analitical").style.display = 'none';
  }

</script>

<style type="text/css">
  #pink{
text-shadow: 0 0 2px #fff, 
             -1px -1px 0 hsl(0, 0%, 0%),
             -2px -2px 1px hsl(0, 0%, 0%),
             -2px -2px 2px hsl(0, 0%, 0%);
  }
</style>

{% endblock %}